# Generated by Django 5.0.4 on 2024-05-04 12:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('city', models.CharField(max_length=50)),
                ('city_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('junction', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('express', 'Express'), ('superfast', 'Superfast'), ('passenger', 'Passenger')], max_length=20)),
                ('no_unreserved', models.IntegerField()),
                ('no_sleeper', models.IntegerField()),
                ('no_chair_car', models.IntegerField()),
                ('no_3ac', models.IntegerField()),
                ('no_2ac', models.IntegerField()),
                ('no_1ac', models.IntegerField()),
                ('runs', models.CharField(max_length=30)),
                ('start_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('marital_stat', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('flat_no', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(6)])),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.TimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='myapp.station')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_routes', to='myapp.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.train')),
            ],
        ),
        migrations.CreateModel(
            name='TrainClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=50)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.train')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('birth_preference', models.CharField(max_length=20)),
                ('seat_number', models.CharField(max_length=10)),
                ('train_class', models.CharField(max_length=5)),
                ('route', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
