# Generated by Django 5.0.4 on 2024-05-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_payment_conveniencefee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
