# Generated by Django 5.0.4 on 2024-05-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_passenger_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
